os: linux
sudo: required
language:
- minimal
services:
- docker

jobs:
  include:
  - name: "checks"
    script:
    - ./scripts/genenv.sh
    #- docker run -v `pwd`:`pwd` -w `pwd` --cap-add=SYS_PTRACE -t rusdevops/bootstrap-cpp scripts/checks.sh


notifications:
    email: false
